export type Icon = JSX.Element;

export interface Icons {
  successScreen?: Icon;
  failedScreen?: Icon;
  success?: Icon;
  warning?: Icon;
  add?: Icon;
  arrow_down?: Icon;
  arrow_up?: Icon;
  add_contractor?: Icon;
  subtract?: Icon;
  alert?: Icon;
  back?: Icon;
  calendar?: Icon;
  clock?: Icon;
  close?: Icon;
  close_check?: Icon;
  close_small?: Icon;
  details?: Icon;
  expand?: Icon;
  expand_more?: Icon;
  expand_primary?: Icon;
  invoice?: Icon;
  paid?: Icon;
  pdf?: Icon;
  post_in?: Icon;
  print?: Icon;
  question?: Icon;
  search?: Icon;
  invoice_display?: Icon;
  modal?: Icon;
  income?: Icon;
  signature?: Icon;
  wallet?: Icon;
  declarations?: Icon;
  expenses?: Icon;
  home?: Icon;
  transaction_expense?: Icon;
  transaction_income?: Icon;
  liquidity?: Icon;
  settings?: Icon;
}
